### ISSUE TITLE
Specifying Version , whats the right string to pass?

### ISSUE THREAD

**Issue by coolgooze** [sous-chefs/mongodb-cookbook#110]
I am trying to use this cookbook to install a specific version of mongodb, however it fails with the below exception

```
       Error executing action `install` on resource 'yum_package[mongodb-org]'
       ================================================================================

       Chef::Exceptions::Package
       -------------------------
       Version 3.2.4 of mongodb-org not found. Did you specify both version and release? (version-release, e.g. 1.84-10.fc6)

       Resource Declaration:
       ---------------------
       # In /tmp/kitchen/cache/cookbooks/qbse_mongodb/recipes/install.rb

        78: package node[:mongodb][:package_name] do
        79:   options packager_opts
        80:   action :install
        81:   version node[:mongodb][:package_version]
        82: end
        83: 

       Compiled Resource:
       ------------------
       # Declared in /tmp/kitchen/cache/cookbooks/qbse_mongodb/recipes/install.rb:78:in `from_file'

       yum_package("mongodb-org") do
         package_name "mongodb-org"
         action [:install]
         retries 0
         retry_delay 2
         default_guard_interpreter :default
         declared_type :package
         cookbook_name "qbse_mongodb"
         recipe_name "install"
         options "--nogpgcheck"
         version "3.2.4"
         flush_cache {:before=>false, :after=>false}
       end
```

I am passing the following attributes

node.default['mongodb']['package_version'] = '3.2.4'

**Comment by djmbm** [comment]
This is actually due to the repository URL needing changed. I'm working on a PR for taking care of this.

**Comment by djmbm** [comment]
I've mostly gotten the changes done for this, but I had missed that prior to my joining the team someone had started a 3.x branch. I need to merge my work with theirs and then submit a PR

**Comment by gsaslis** [comment]
@djmbm any luck with his?

**Comment by shortdudey123** [comment]
For the above example, the error message gives the solution `(version-release, e.g. 1.84-10.fc6)` => `3.2.4-1.el7`

Cookbook is pending a rewrite for 3.x, so i will close this in the time being.  Reopen if the above suggestion does not work (outside of the repo changing)

**Comment by djmbm** [comment]
@gsaslis No, I've not yet had time to merge my changes and theirs, it isn't a trivial merge.
